name: Ci-Cd-Pipeline-to-AWS

env:
  EB_PACKAGE_S3_BUCKET_NAME: "crystall-fastapi-app-packages"  # Corrected spelling
  EB_APPLICATION_NAME: "FastApiCr"
  EB_ENVIROMENT_NAME:  "FastApiCr-env-1"
  DEPLOY_PACKAGE_NAME:  "CrystalPuzzles_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches:
      - release  # Correct trigger syntax
      

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello World  # Correct indentation
        run: echo "Hello World"  
      - name: Checkout Repository from specific branch
        uses: actions/checkout@v3
        with:
          ref: release  
      - name: Check workspace contents
        run: ls -R $GITHUB_WORKSPACE 
      - name: Check teh current directory
        run: ls -a
      - name: find_docker_compose
        run: |
          result=$(find $GITHUB_WORKSPACE -name "docker-compose.yml")
          if [ -z "$result" ]; then
            echo "docker-compose.yml not found"
            exit 1  # Завершить выполнение
          else
            directory=$(dirname "$result")
            echo "Found docker-compose.yml at: $result"
            echo "Directory path is: $directory"
            echo "docker_compose_path=$directory" >> $GITHUB_OUTPUT
          fi

      - name: Check services healthiness
        uses: thegabriele97/dockercompose-health-action@main
        with:
          filename: 'docker-compose.yml'
          timeout: '60'
          workdir: ${{ steps.find_docker_compose.outputs.docker_compose_path }}
      - name: Check Services
        run: |
          docker-compose ps
      - name: Shut Down Docker Compose
        if: always() 
        run: docker-compose -f docker-compose.yml down
        
        
  # integration:
  #   runs-on: ubuntu-latest
  #   needs: [tests]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
        
  #     - name: Create ZIP deployment package
  #       run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v3
  #       with:
  #         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
  #         aws-region: ${{ env.AWS_REGION_NAME }}

  #     - name: Debug environment variables
  #       run: echo ${{ env.EB_PACKAGE_S3_BUCKET_NAME }}

  #     - name: Copy Deployment package to S3 bucket
  #       run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

  #     - name: Print message for task end
  #       run: echo "Task for S3 complete"


  # deployment:
  #   runs-on: ubuntu-latest
  #   needs: [integration]

  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v3
  #       with:
  #         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
  #         aws-region: ${{ env.AWS_REGION_NAME }}

  #     - name: Create new Elastic Beanstalk Application Version
  #       run: |
  #         aws elasticbeanstalk create-application-version \
  #           --application-name ${{ env.EB_APPLICATION_NAME }} \
  #           --version-label "Ver-${{ github.sha }}" \
  #           --source-bundle S3Bucket=${{ env.EB_PACKAGE_S3_BUCKET_NAME }},S3Key=${{ env.DEPLOY_PACKAGE_NAME }} 
            
  #     - name: Update Elastic Beanstalk Environment Configuration
  #       run: |
  #         aws elasticbeanstalk update-environment \
  #           --environment-name ${{ env.EB_ENVIROMENT_NAME }} \
  #           --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,Value=t4g.medium \
  #           --version-label "Ver-${{ github.sha }}"            

  #     - name: Print message for task end
  #       run: echo "The deployment task is complete"        

      
      
