name: Ci-Cd-Pipeline-to-AWS

env:
  EB_PASKAGE_S3_BUCKET_NAME: "crystall-fastapi-app-packages"
  EB_APPLICATION_NAME: "FastApiCr"
  EB_ENVIROMENT_NAME:  "FastApiCr-env"
  DEPLOY_PACKAGE_NAME:  "CrystalPuzzles_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hellow Word
      run: echo "Helow Word"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
  

  

      
