name: Deploy by ssh

env:
  SSH_USERNAME: "ubuntu"  
  SSH_HOST_NAME: "ec2-35-157-192-134.eu-central-1.compute.amazonaws.com"
  SSH_PORT: "22"

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change directory permitions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST_NAME }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            sudo chmod 777 -R /home/ubuntu/Crystall/

      - name: Stop docker conteiners and clean docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST_NAME }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            docker stop $(docker ps -aq) && \
            docker system prune --all --force
            
      - name: Refresh content
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Sync Repository via SSH    
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete \
          . ubuntu@ec2-35-157-192-134.eu-central-1.compute.amazonaws.com:Crystall
      - name: Start docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST_NAME }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            docker compose -f /home/ubuntu/Crystall/docker-compose.yml up -d

