name: Deploy by ssh

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change directory permitions
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-122-254-89.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            sudo chmod 777 -R /home/ubuntu/Crystall/

      - name: Stop docker conteiners and clean docker images
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-122-254-89.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -aq) && \
            docker system prune --all --force
            
      - name: Refresh content
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Sync Repository via SSH    
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete \
          . ubuntu@ec2-3-122-254-89.eu-central-1.compute.amazonaws.com:Crystall
      - name: Start docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-122-254-89.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            docker compose -f /home/ubuntu/Crystall/docker-compose.yml up -d

      # - name: stop docker
      #   run: docker compose -f /home/ubuntu/Crystall/docker-compose.yml down
      # - name: clean images
      #   run: docker system prune --all --force
      # - name: up docker compose
      #   run: docker compose -f /home/ubuntu/Crystall/docker-compose.yml up -d
